<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;

class SurveySeeder extends Seeder
{
    protected $toTruncate = ['surveys','survey_answers','survey_categories','survey_questions'];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        Model::unguard();

        foreach ($this->toTruncate as $table) {
            DB::table($table)->truncate();
        }

        $positiveAnswers = json_encode([
            '2' => 'Strongly Disagree',
            '1' => 'Disagree',
            '0' => 'Neutral',
            '-1' => 'Agree',
            '-2' => 'Strongly Agree',
        ]);

        $negativeAnswers = json_encode([
            '-2' => 'Strongly Disagree',
            '-1' => 'Disagree',
            '0' => 'Neutral',
            '1' => 'Agree',
            '2' => 'Strongly Agree',
        ]);

        DB::table('surveys')->insert([
            [
                'title' => 'Survey',
                'created_at' =>  \Carbon\Carbon::now(), # \Datetime()
                'updated_at' => \Carbon\Carbon::now(),  # \Datetime()
            ],
        ]);

        DB::table('survey_categories')->insert([
//            [
//                'survey_id' => 1,
//                'title' => 'Individual',
//                /                'created_at' =>  \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ],
            [
                'survey_id' => 1,
                'title' => 'Calculated',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Spontaneous',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Introvert',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Extrovert',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Healthy',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Unhealthy',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Mood Instability',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Mood Stability',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Communication Direct',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Communication Indirect',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],[
                'survey_id' => 1,
                'title' => 'Realist',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Idealist',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Liberal',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Conservative',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Cultured',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Uncultured',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Family Oriented',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Friend Oriented',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Maximizer',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'survey_id' => 1,
                'title' => 'Satisfier',
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ]
        ]);

        DB::table('survey_questions')->insert([
//            [
//                'category_id' => 1,
//                'question' => 'Age',
//                'created_at' =>  \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Married',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Children',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Pet',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Education',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Religion',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Gender',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Sexual orientation',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//
//            ], [
//                'category_id' => 1,
//                'question' => 'Time since last relapse',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Smoker',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Attending support groups',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
//            ], [
//                'category_id' => 1,
//                'question' => 'Location',
//                'created_at' => \Carbon\Carbon::now(),
//                'updated_at' => \Carbon\Carbon::now(),
            [
                'category_id' => 1,
                'question' => 'I respond to e-mails as soon as possible and hate seeing unread emails',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 1,
                'question' => 'Being organized is better than being flexible',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 1,
                'question' => 'My personal and professional spaces are very well organized',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 1,
                'question' => 'When booking trips, I create a minute-by-minute itinerary',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 1,
                'question' => 'I know what I will eat for dinner 2 days before I have it',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 2,
                'question' => 'I improvise more than I plan',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 2,
                'question' => 'I accomplish most by working while motivated rather than systematically approaching the task',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 2,
                'question' => 'I wait until the night before to complete a task',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 2,
                'question' => 'I am witty and a quick thinker',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 2,
                'question' => 'I’d rather try a new restaurant than to return to my favorite spot',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 3,
                'question' => 'I typically wait for others to start conversations with me',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 3,
                'question' => 'I’d prefer to play video games or read a book than attend a social gathering',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 3,
                'question' => 'I’m the most quiet of my family/friends',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 3,
                'question' => 'I enjoy listening more than speaking',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 3,
                'question' => 'Being surrounded by others often leaves me feeling drained',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 4,
                'question' => 'I’m the most fun person while with family and friends',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 4,
                'question' => 'People tell me how funny I am',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 4,
                'question' => 'I’m the center of the dance circle',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 4,
                'question' => 'My best thinking happens when I am in a group',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 4,
                'question' => 'I enjoy making small talk',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 5,
                'question' => 'I exercise 2-3 times a week',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 5,
                'question' => 'I try to eat organic',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 5,
                'question' => 'I avoid foods that aren’t considered “healthy”',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 5,
                'question' => 'I prefer to drink water instead of other beverages',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 5,
                'question' => 'I take vitamins',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 6,
                'question' => 'I would like to be much healthier than I am',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 6,
                'question' => 'I don’t count calories or look at nutritional values',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 6,
                'question' => 'I eat fast food',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 6,
                'question' => 'The food I eat doesn’t impact how I feel',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 6,
                'question' => 'Sleep is not important to me',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 7,
                'question' => 'It is difficult for me to improve my mood if I’m feeling down',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 7,
                'question' => 'My mood can change very quickly',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 7,
                'question' => 'The weather heavily impacts my mood',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 7,
                'question' => 'Other people’s moods can heavily impact mine',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 7,
                'question' => 'I become irritable easily',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 8,
                'question' => 'I can easily control my emotions',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 8,
                'question' => 'I feel as though I am emotionally stable',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 8,
                'question' => 'Music can improve my mood',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 8,
                'question' => 'I feel comfortable expressing my emotions',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 8,
                'question' => 'I handle stressful situations well',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 9,
                'question' => 'I don’t beat around the bush when I have something to say',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 9,
                'question' => 'I’m more concerned about telling the truth than other’s feelings',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 9,
                'question' => 'Friends and family ask me for help making decisions',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 9,
                'question' => 'I try to deal with any and all issues as soon as possible',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 9,
                'question' => 'Others often tell me I can be abrasive',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 10,
                'question' => 'I am open to hearing everyone’s opinions',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 10,
                'question' => 'I consider myself to be a people pleaser',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 10,
                'question' => 'I try to figure things out on my own rather than asking someone for help',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 10,
                'question' => 'I stay quiet when others are arguing because I don’t want to cause more problems',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 10,
                'question' => 'I have a difficult time expressing my opinions and myself',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 11,
                'question' => 'After winning the lottery, the first thing I do is create a financial plan',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 11,
                'question' => 'I prefer to watch documentaries instead of fictional shows',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 11,
                'question' => 'My dreams tend to focus on the real world and its events',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 11,
                'question' => 'Most of my downtime consists of thinking of my to-do list',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 11,
                'question' => 'I plan for my future and “what’s next”',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 12,
                'question' => 'I think about having a superpower',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 12,
                'question' => 'I find myself daydreaming when I get bored',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 12,
                'question' => 'I imagine what animals would say if they could speak',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 12,
                'question' => 'People tell me I am carefree',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 12,
                'question' => 'On a long drive, my mind starts to fantasize about my dreams',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 13,
                'question' => 'I am pro-choice',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 13,
                'question' => 'I believe in marriage equality',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 13,
                'question' => 'I believe minimum wage should be $15 nationwide',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 13,
                'question' => 'I think there should be universal healthcare',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 13,
                'question' => 'It is important for all nations to work together to combat climate change',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 14,
                'question' => 'Having the strongest armed forces should be our country’s number one priority',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 14,
                'question' => 'I believe that undocumented immigrants should be deported regardless of circumstance',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 14,
                'question' => 'I support the death penalty',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 14,
                'question' => 'Individuals should be able to carry a concealed weapon at all times',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 14,
                'question' => 'I find it very important that children respect anyone with authority',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 15,
                'question' => 'I am interested in speaking another language',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 15,
                'question' => 'Other cultures interest me',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 15,
                'question' => 'I enjoy museums',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 15,
                'question' => 'I would like to live in another country',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 15,
                'question' => 'I find myself daydreaming about traveling',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 16,
                'question' => 'I don’t care about what is happening in other countries',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 16,
                'question' => 'I do not enjoy reading',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 16,
                'question' => 'I don’t find it important to keep up with current world events',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 16,
                'question' => 'I don’t usually try new foods',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 16,
                'question' => 'I do not care if I ever travel outside the country',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 17,
                'question' => 'I prefer to hang out with my family instead of friends',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 17,
                'question' => 'I eat dinner with my family at least once a week',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 17,
                'question' => 'I communicate with family members more than friends',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 17,
                'question' => 'My family is always there for me',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 17,
                'question' => 'I look for the approval of my family',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 18,
                'question' => 'I like to keep distance from my family',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 18,
                'question' => 'I live far away from my family',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 18,
                'question' => 'I prefer to share important life events with friends instead of family',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 18,
                'question' => 'I trust friends more than family',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 18,
                'question' => 'I have little communication with family',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 19,
                'question' => 'I set the bar very high for myself and expect to live up to my expectations',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 19,
                'question' => 'I feel disappointed when my expectations aren’t met',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 19,
                'question' => 'I find it important when shopping to compare products to find the best one',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 19,
                'question' => 'I find myself wishing I could time travel to “redo” decisions I have made',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 19,
                'question' => 'Even if I am satisfied with my current job, I still look for other positions out of curiosity',
                'type' => 'checkbox',
                'options' => $negativeAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 20,
                'question' => 'I go with my “gut” when making decisions',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 20,
                'question' => 'I find it easy to let go of mistake I’ve made and learn from them',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 20,
                'question' => 'I am happy with the life that I have',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 20,
                'question' => 'I have no issue making decisions',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ], [
                'category_id' => 20,
                'question' => 'I don’t consider myself a perfectionist',
                'type' => 'checkbox',
                'options' => $positiveAnswers,
                'created_at' =>  \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ]
        ]);

        Model::unguard();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    }
}
