export interface UserInterface {
    id: number,
    name: string,
    email: string,
    password: string,
    status: string,
    reset_password_token?: string,
    age?: number,
    married?: boolean,
    children?: boolean,
    pet?: boolean,
    education?: string,
    religion?: string,
    gender?: string,
    sex_orientation?: string,
    last_relaps?: string,
    smoker?: boolean,
    support_groups?: any[],
    city?: string,
    zip_code?: number,
    state?: string,
    created_at?: string,
    updated_at?: string,
    deleted_at?: string,
    token: any
}
